### ISSUE TITLE
User Module, Entity and Service

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/api#18]
### What Functionality Are You Suggesting?
To start our work on supporting users we need a new user module that houses a user entity and user service. The user service should include the ability to:
- Get one specific user by ID
- Get one specific user by Auth ID
- Get all users
- Create a new user
- Update a user by ID

A user entity should have:
- An auto-incrementing, unique and primary key `id` field (e.g. `1`)
- A unique `auth_id` field (e.g. `auth0|6237590b647a36006ba3c6ea`)
- A unique `username` field (e.g. `johnsmith`)
- A `created` field which contains the date at which the entity was created
- A `modified` field which's value updates each time the entity is modified

You can use the [`@CreateDateColumn()`](https://typeorm.io/decorator-reference#createdatecolumn) and [`@UpdatedDateColumn()`](https://typeorm.io/decorator-reference#updatedatecolumn) decorators to automatically handle the dates.

### Why Will This Benefit The Community?
This will allow us to create and retrieve users throughout the API, therefore unlocking the ability to serve them across the web and Discord.

**Comment by JonaVDM** [comment]
Working on it!
