### ISSUE TITLE
Get User Endpoint

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/api#22]
### What Functionality Are You Suggesting?
The ability to get a specific user from the database via the API.

## API Endpoint
`GET /user/:id`

Users are not required to be authenticated to access this endpoint.

### Response Body
```ts
{
    id: number;
    username: string;
    created: string; // simplified extended ISO formatted date
    modified: string; // simplified extended ISO formatted date 
}
```

### Why Will This Benefit The Community?
This functionality will allow us to display user profiles on the web and in Discord.

**Comment by JonaVDM** [comment]
Oh right, assigning stuff. You can assign me Lambo :melon:
