### ISSUE TITLE
Article Module, Entity and Service

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/api#27]
### What Functionality Are You Suggesting?
To start our work on supporting articles we need a new article module that houses an article entity and article service. The article service should include the ability to:
- Get one specific article by ID
- Get all articles
- Create a new article
- Update an article by ID

An article entity should have:
- An auto-incrementing, unique and primary key `id` field (e.g. `1`)
- A `created` field which contains the date at which the entity was created
- A `modified` field which's value updates each time the entity is modified
- A `user` field which's value is equal to the ID of the user who created the article
    - In the entity, we should join the `article` and `user` tables together so that it contains a full copy of the user
- A `title` field which's value is a string which is the title of the article
- A `slug` field which's value is a unique string which is the path to the article 
- A `status` field which's value is an enum of `APPROVED`, `PENDING`, `REJECTED` (default of `PENDING`)
- A `description` field which is a string (max length of 250 characters)
- A `content` field which is a string

You can use the [`@CreateDateColumn()`](https://typeorm.io/decorator-reference#createdatecolumn) and [`@UpdatedDateColumn()`](https://typeorm.io/decorator-reference#updatedatecolumn) decorators to automatically handle the dates.

### Why Will This Benefit The Community?
This will allow us to create and retrieve articles throughout the API, therefore unlocking the ability to serve them across the web and Discord.

**Comment by JonaVDM** [comment]
🍉
