### ISSUE TITLE
Setup Database ORM

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/api#3]
Blocked by #1 

### What Functionality Are You Suggesting?
We want to set up an ORM so that we can interact with our database. This can be achieved through TypeORM and is documented [here](https://docs.nestjs.com/techniques/database) (note this uses MySQL in the example, but we want to use PostgreSQL).

You do not need to set up any repositories as part of this ticket, just the initial connection.

The following environment variables should be used for the database connection:
- `DATABASE_HOST` (`host)`
- `DATABASE_PORT` (`port`)
- `DATABASE_USER` (`username`)
- `DATABASE_PASS` (`password`)
- `DATABASE_NAME` (`database`)

If `NODE_ENV` is not `production` then `synchronize` should be `true`.

We should also have a Docker Compose setup for running the API and database together.

### Why Will This Benefit The Community?
This will benefit us by allowing us to have a place where we can save and retrieve data from.

**Comment by J141** [comment]
I'll pick up this issue.
