### ISSUE TITLE
Setup Swagger

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/api#4]
Blocked by #1 

### What Functionality Are You Suggesting?
We want to set up a swagger document that automatically contains all the documentation for the API. This functionality is described on the NestJS documentation [here](https://docs.nestjs.com/openapi/introduction).

### Why Will This Benefit The Community?
This will allow developers who are working on the frontend to easily see how to save and retrieve data to and from the API.

**Comment by JonaVDM** [comment]
I can tackle this one!
